###
# docker-compose.yml for testing and experimentation
###

services:
  unidata-tomcat:
    image: tomcat-docker:11-jdk17
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./logs/:/usr/local/tomcat/logs/
    env_file:
      - "compose.env"
