#+options: ':nil *:t -:t ::t <:t H:4 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+options: auto-id:t
#+options: H:6

#+title: readme
#+date: <2023-04-20 Thu>
#+author: Julien Chastang
#+email: chastang@ucar.edu
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.3 (Org mode 9.2.1)

#+property: :eval no :results none

#+STARTUP: overview

* Setup                                                            :noexport:
  :PROPERTIES:
  :CUSTOM_ID: h-A21B78FB
  :END:

#+begin_src emacs-lisp :eval yes
  (setq org-confirm-babel-evaluate nil)
#+end_src


#+begin_src emacs-lisp :eval yes
  (setq base-dir (concat (projectile-project-root) ".org"))

  (setq pub-dir (projectile-project-root))

  (setq org-publish-project-alist
        `(("unidata-tomcat-readme"
            :base-directory ,base-dir
            :recursive t
            :base-extension "org"
            :publishing-directory ,pub-dir
            :publishing-function org-gfm-publish-to-gfm)))
#+end_src

* Unidata Tomcat Docker
:PROPERTIES:
:CUSTOM_ID: h-C944C5F1
:END:

A security-hardened Tomcat container for [[https://github.com/Unidata/thredds-docker][thredds-docker]] and [[https://github.com/Unidata/ramadda-docker][ramadda-docker]].

** Introduction
:PROPERTIES:
:CUSTOM_ID: h-1411CF81
:END:

This repository contains files necessary to build and run a security hardened Tomcat Docker container, based off of a canonical [[https://hub.docker.com/_/tomcat/][Tomcat base image]]. The Unidata Tomcat Docker images associated with this repository are [[https://hub.docker.com/r/unidata/tomcat-docker/][available on Docker Hub]]. All default web applications have been expunged from this container so it will primarily serve as a base image for other containers.

*** Security Hardening Measures
   :PROPERTIES:
   :CUSTOM_ID: h-6C9EE33A
   :END:

**** Introduction
:PROPERTIES:
:CUSTOM_ID: h-F5641083
:END:
This image includes the security-related configuration changes listed below. Deployment and application security require additional configuration and validation.

- Eliminated default Tomcat web applications
- Run Tomcat with unprivileged user ~tomcat~ (via ~entrypoint.sh~)
- Only writable Tomcat runtime directories (~CATALINA_HOME/logs~, ~CATALINA_HOME/temp~, and ~CATALINA_HOME/work~) are owned by user ~tomcat~ (via ~entrypoint.sh~). Ownership and permissions elsewhere in ~CATALINA_HOME~, including ~conf~, ~bin~, ~lib~, and ~webapps~, are left unchanged.

In your runtime configuration, ensure ~server.xml~ and ~web.xml~ bind mounts are read-only. This prevents the Tomcat process from modifying configuration files supplied by the host and is a recommended security practice. For example, with Docker Compose:

#+begin_src yaml
- ./files/server.xml:/usr/local/tomcat/conf/server.xml:ro
- ./files/web.xml:/usr/local/tomcat/conf/web.xml:ro
#+end_src

**** web.xml Enhancements
    :PROPERTIES:
    :CUSTOM_ID: h-76CE835C
    :END:

The following changes have been made to [[./web.xml][web.xml]] from the out-of-the-box version:

- Added ~SAMEORIGIN~ anti-clickjacking option
- HTTP header security filter (~httpHeaderSecurity~) uncommented/enabled

**** server.xml Enhancements
    :PROPERTIES:
    :CUSTOM_ID: h-8027E0B0
    :END:

The following changes have been made to [[./server.xml][server.xml]] from the out-of-the-box version:

- Server version information is obscured to user via ~server~ attribute for all ~Connector~ elements
- Shutdown port disabled
- Tomcat-generated error responses omit stack traces, error details, and server information via ~ErrorReportValve~. Application-defined error responses must separately avoid exposing sensitive details.
- Digested passwords. See next section.

The active ~Connector~  has ~relaxedPathChars~ and ~relaxedQueryChars~ attributes. This change may not be optimal for security, but must be done [[https://github.com/Unidata/thredds-docker/issues/209][to accommodate DAP requests]] which THREDDS and RAMADDA must perform.

**** Digested Passwords
    :PROPERTIES:
    :CUSTOM_ID: h-4CE92D2E
    :END:

This container has a ~UserDatabaseRealm~, ~Realm~ element in ~server.xml~ with a default ~CredentialHandler~ ~algorithm~ of ~sha-512~. This modification is an improvement over the clear text password default that comes with the parent container (~tomcat:8.5-jdk11~). Passwords defined in ~tomcat-users.xml~ must use digested passwords in the ~password~ attributes of the ~user~ elements. Generating a digested password is simple. Here is an example for the ~sha-512~ digest algorithm:

#+begin_src sh
  docker run tomcat  /usr/local/tomcat/bin/digest.sh -a "sha-512" mysupersecretpassword
#+end_src

This command will yield something like:

#+begin_src sh
  mysupersecretpassword:94e334bc71163a69f2e984e73741f610e083a8e11764ee3e396f6935c3911f49$1$a5530e17501f83a60286f6363a8647a277c9cfdb
#+end_src

The hash after the ~:~ is what you will use for the ~password~ attribute in ~tomcat-users.xml~.

More information about this topic is available in the  [[https://tomcat.apache.org/tomcat-8.5-doc/realm-howto.html#Digested_Passwords][Tomcat documentation]].

**** CVEs
:PROPERTIES:
:CUSTOM_ID: h-C1DF14EF
:END:

We strive to maintain the security of this project's DockerHub images by updating them with the latest upstream security improvements. If you have any security concerns, please email us at [[mailto:security@unidata.ucar.edu][security@unidata.ucar.edu]] to bring them to our attention.

** Versions
   :PROPERTIES:
   :CUSTOM_ID: h-6C0AB867
   :END:

See tags listed [[https://hub.docker.com/r/unidata/tomcat-docker/tags][on dockerhub]]. Note, these versions are not necessarily static and will evolve due to upstream image changes. It's recommended to check regularly to ensure you have the latest image.

** Prerequisites
:PROPERTIES:
:CUSTOM_ID: h-61809CB7
:END:

Before you begin using this Docker container project, make sure your system has Docker installed. Docker Compose is optional but recommended.

** Installation
:PROPERTIES:
:CUSTOM_ID: h-FB3558BB
:END:

You can either pull the image from DockerHub with:

#+begin_src sh
  docker pull unidata/tomcat-docker:<version>
#+end_src

Or you can build it yourself with:

  1. **Clone the repository**: ~git clone https://github.com/Unidata/tomcat-docker.git~
  2. **Navigate to the project directory**: ~cd tomcat-docker~
  3. **Build the Docker image**: ~docker build -t tomcat-docker:<version>~ .

** Usage
:PROPERTIES:
:CUSTOM_ID: h-B602CE28
:END:

Note that this project is meant to serve as a base image for other containerized Docker Tomcat web applications. Refer to the image created by this project in your Dockerfile. For example:

#+begin_src sh
  FROM unidata/tomcat-docker:8.5-jdk11
#+end_src

Sometimes it is useful to enter this container via bash and poke around, just to see what is there. For example,

#+begin_src sh
  docker run -it unidata/tomcat-docker:8.5-jdk11 bash
#+end_src

** Configuration
:PROPERTIES:
:CUSTOM_ID: h-AFA7F4DC
:END:
*** Configurable Tomcat UID and GID
   :PROPERTIES:
   :CUSTOM_ID: h-E4632DC9
   :END:

The problem with mounted Docker volumes and UID/GID mismatch headaches is best explained here: https://denibertovic.com/posts/handling-permissions-with-docker-volumes/.

This container allows the possibility of controlling the UID/GID of the ~tomcat~ user inside the container via ~TOMCAT_USER_ID~ and ~TOMCAT_GROUP_ID~ environment variables. If not set, the default UID/GID is ~1000/1000~. For example,

#+begin_src sh
  docker run --name tomcat \
       -e TOMCAT_USER_ID=`id -u` \
       -e TOMCAT_GROUP_ID=`getent group $USER | cut -d':' -f3` \
       -v `pwd`/logs:/usr/local/tomcat/logs/ \
       -v  /path/to/your/webapp:/usr/local/tomcat/webapps \
       -d -p 8080:8080 unidata/tomcat-docker:<version>
#+end_src

where ~TOMCAT_USER_ID~ and ~TOMCAT_GROUP_ID~ have been configured with the UID/GID of the user running the container. If using ~docker-compose~, see ~compose.env~ to configure the UID/GID of user ~tomcat~ inside the container.

This feature enables greater control of file permissions written outside the container via mounted volumes (e.g., files contained within the Tomcat logs directory such as ~catalina.out~).

Note that containers that inherit this container and have overridden ~entrypoint.sh~ will have to take into account user ~tomcat~ is no longer assumed in the ~Dockerfile~. Rather the ~tomcat~ user is now created within the ~entrypoint.sh~ and those overriding ~entrypoint.sh~ should take this fact into account.  Also note that this UID/GID configuration option will not work on operating systems where Docker is not native (e.g., macOS).

*** HTTPS
   :PROPERTIES:
   :CUSTOM_ID: h-D725A36E
   :END:

This Tomcat container can support HTTPS for either self-signed certificates which can be useful for experimentation or certificates from a CA for a production server. For a complete treatment on this topic, see https://tomcat.apache.org/tomcat-8.5-doc/ssl-howto.html.

**** Self-signed Certificates
    :PROPERTIES:
    :CUSTOM_ID: h-C24884FC
    :END:

For local HTTPS testing, generate a 30-day self-signed RSA certificate. This certificate is not intended for production.

#+begin_src sh
  openssl req -new -newkey rsa:4096 -sha256 -days 30 -nodes -x509 \
      -subj "/CN=localhost" \
      -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
      -keyout ./ssl.key -out ./ssl.crt
  chmod 600 ./ssl.key
#+end_src

The private key must be owned by the Tomcat runtime UID (1000 by default) for the 600 permissions above.

Then augment the ~server.xml~ from this repository with this additional XML snippet for [[https://tomcat.apache.org/tomcat-11.0-doc/ssl-howto.html][Tomcat TLS capability]]:

#+begin_src xml
  <Connector port="8443"
             protocol="org.apache.coyote.http11.Http11NioProtocol"
             maxThreads="150"
             enableLookups="false"
             disableUploadTimeout="true"
             acceptCount="100"
             SSLEnabled="true">
    <SSLHostConfig>
      <Certificate certificateFile="${catalina.base}/conf/ssl.crt"
                   certificateKeyFile="${catalina.base}/conf/ssl.key" />
    </SSLHostConfig>
  </Connector>
#+end_src

Mount the configuration, certificate, and private key read-only. Publish HTTPS on loopback for this local test:

#+begin_src sh
  docker run -d -p 127.0.0.1:8443:8443 \
      -v "$PWD/server.xml:/usr/local/tomcat/conf/server.xml:ro" \
      -v "$PWD/ssl.crt:/usr/local/tomcat/conf/ssl.crt:ro" \
      -v "$PWD/ssl.key:/usr/local/tomcat/conf/ssl.key:ro" \
      tomcat-docker:<version>
#+end_src

Alternatively, after building the image, use this ~docker-compose.yml~ with ~docker compose up -d~:

#+begin_src yaml
  services:
    unidata-tomcat:
      image: tomcat-docker:<version>
      ports:
        - "127.0.0.1:8443:8443"
      volumes:
        - ./ssl.crt:/usr/local/tomcat/conf/ssl.crt:ro
        - ./ssl.key:/usr/local/tomcat/conf/ssl.key:ro
        - ./server.xml:/usr/local/tomcat/conf/server.xml:ro
#+end_src

After Tomcat starts:

#+begin_src sh
  curl --cacert ./ssl.crt https://localhost:8443/
#+end_src

**** Certificate from CA
    :PROPERTIES:
    :CUSTOM_ID: h-B5E124BB
    :END:

Obtain a server certificate (~ssl.crt~), its private key (~ssl.key~), and any intermediate CA certificates (~intermediates.crt~), in PEM format. Do not include the root CA certificate.

Create a PKCS12 keystore:

#+begin_src sh
  openssl pkcs12 -export \
      -in ssl.crt \
      -inkey ssl.key \
      -certfile intermediates.crt \
      -name mydomain.com \
      -out keystore.p12
#+end_src

OpenSSL will prompt for the password protecting ~keystore.p12~.

Add this connector inside the ~Service~ element in ~server.xml~:

#+begin_src xml
  <Connector port="8443"
             protocol="org.apache.coyote.http11.Http11NioProtocol"
             SSLEnabled="true">
    <SSLHostConfig protocols="TLSv1.2,TLSv1.3">
      <Certificate certificateKeystoreFile="${catalina.base}/conf/keystore.p12"
                   certificateKeystoreType="PKCS12"
                   certificateKeyAlias="mydomain.com"
                   certificateKeystorePassword="xxxx" />
    </SSLHostConfig>
  </Connector>
#+end_src

Replace ~xxxx~ with the password entered when creating the keystore.

Mount ~server.xml~ and the keystore read-only, using your locally built ~tomcat-docker:<version>~ image:

#+begin_src sh
  docker run -d -p 127.0.0.1:8443:8443 \
      -v "$PWD/server.xml:/usr/local/tomcat/conf/server.xml:ro" \
      -v "$PWD/keystore.p12:/usr/local/tomcat/conf/keystore.p12:ro" \
      tomcat-docker:<version>
#+end_src

The PKCS12 keystore contains the private key, so restrict access to it while ensuring it is readable by the Tomcat runtime user.

** Testing
:PROPERTIES:
:CUSTOM_ID: h-32889858
:END:

If you would like to do a small test to ensure the Unidata Tomcat Docker image is working:

#+begin_src sh
  mkdir -p /tmp/test
  wget -O /tmp/test/sample.war https://tomcat.apache.org/tomcat-8.5-doc/appdev/sample/sample.war
  docker run --name tomcat -e TOMCAT_USER_ID=1000 -e TOMCAT_GROUP_ID=1000 -v /tmp/test/:/usr/local/tomcat/webapps -d -p 8080:8080 unidata/tomcat-docker:<version>
  curl  http://127.0.0.1:8080/sample/index.html
#+end_src

This should yield some HTML that starts like this:

#+begin_src html
  <html>
  <head>
  <title>Sample "Hello, World" Application</title>
  </head>
  ...
#+end_src
